### ISSUE TITLE
phil parameters not recognized by phenix.refine?

### ISSUE THREAD

**Issue by spmeisburger** [rs-station/matchmaps#46]
phenix version: 1.21-5207

Tried matchmaps for the first time on some in-house data, and it failed at the first phenix.refine step.

```bash
matchmaps --mtzoff lysozyme_0MPa.mtz F SIGF \
    --mtzon lysozyme_540MPa.mtz F SIGF \
    --pdboff lysozyme_0MPa.pdb \
    --input-dir . \
    --output-dir lysozyme_540MPa
    --verbose
```

I re-ran with --verbose flag, and I see that phenix produces the following output:

```
 Unrecognized PHIL parameters:
  -----------------------------
    refinement.input.pdb.file_name (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 9)
    refinement.input.xray_data.file_name (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 12)
    refinement.input.xray_data.labels (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 13)
    refinement.input.xray_data.r_free_flags.generate (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 15)
    refinement.input.xray_data.force_anomalous_flag_to_be_equal_to (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 17)
    refinement.output.prefix (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 24)
    refinement.output.serial (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 25)
    refinement.output.serial_format (file "lysozyme_540MPa/params_lysozyme_540MPa_scaled_truecell_rbr_to_lysozyme_0MPa_nospecialpositions_renumbered_0.eff", line 26)

Sorry: Some PHIL parameters are not recognized by phenix.refine.
 Please run this program with the --show-defaults option to see what parameters
are available.
```

Some of those flags do appear when I run `phenix.refine --show-defaults`, I'm not sure exactly what's wrong here. Perhaps formatting of the phil file? Or phenix version?

**Comment by spmeisburger** [comment]
After rolling back to an older version of phenix (version: 1.20-4459) it worked fine.

**Comment by dennisbrookner** [comment]
Thanks for raising this - this is really weird! At a first glance, I don't see anything in the phenix 1.21 release notes about changes to PHIL formatting. I'm glad that fixed the issue though! I'll dig into this a little more and check back here.

**Comment by mysecondnameisdanger** [comment]
Happened the same with some bash scripts I had using `phenix.refine` and also with `qfit3` https://github.com/ExcitedStates/qfit-3.0/issues/415.

**Comment by dennisbrookner** [comment]
Thanks, this is good to know! It seems like the best short-term solution is to just clarify in the documentation that phenix 1.21 is not currently supported.

@mysecondnameisdanger , do you have a working example of a refinement `.eff` file for phenix 1.21? Specifically,  I don't see anything in the "List of all available keywords" about a replacement for `input.pdb.file_name`, `input.xray_data.file_name`, or `output.prefix`, all of which seem pretty essential!
https://phenix-online.org/documentation/reference/refinement.html#list-of-all-available-keywords
